"""initial database structure

Revision ID: 371a23dc978c
Revises: None
Create Date: 2016-04-14 00:19:10.555745

"""

# revision identifiers, used by Alembic.
revision = '371a23dc978c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
